site_name: Webengineering Lectures
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - Folien:
      Einführung: folien/einfuehrung.pdf
  - React:
      - react/getting_started.md
      - react/setting_up.md
      - react/components.md
      - react/props.md
      - react/map_list_keys.md
      - react/hooks.md
      - react/conditional_rendering.md
      - react/events.md
      - react/forms.md
      - react/component_lifecycles.md
      - react/controlled_versus_uncontrolled.md
      - react/context.md
      - react/custom_hooks.md
      - react/fetch_and_useQuery.md
      - react/react-router.md
      - react/chakra-ui.md
      - react/project_structure.md
  - Exercises:
      - exercises/index.md
      - exercises/promises.md
      - exercises/01_javascript/index.md
      - exercises/02_web_ui/index.md
      - exercises/react.md
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
