site_name: React Lecture
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - Exercises:
      - JavaScript:
          - exercises/javascript_fundamentals/arrays.md
          - exercises/javascript_fundamentals/classes.md
          - exercises/javascript_fundamentals/conditionals.md
          - exercises/javascript_fundamentals/data_types.md
          - exercises/javascript_fundamentals/destructuring_and_spreading.md
          - exercises/javascript_fundamentals/functions.md
          - exercises/javascript_fundamentals/object.md
          - exercises/javascript_fundamentals/promises.md
      - React:
          - exercises/react/index.md
          - exercises/react/components.md
          - exercises/react/events.md
          - exercises/react/map_list_keys.md
          - exercises/react/props.md
          - exercises/react/setting_up.md
          - react/conditional_rendering.md
  - JavaScript Fundamentals:
      - javascript_fundamentals/index.md
      - javascript_fundamentals/setup.md
      - javascript_fundamentals/adding_javascript_to_a_webpage.md
      - javascript_fundamentals/variables.md
      - javascript_fundamentals/data_types.md
      - javascript_fundamentals/arrays.md
      - javascript_fundamentals/conditionals.md
      - javascript_fundamentals/loops.md
      - javascript_fundamentals/scope.md
      - javascript_fundamentals/object.md
      - javascript_fundamentals/functions.md
      - javascript_fundamentals/higher_order_functions.md
      - javascript_fundamentals/promises.md
      - javascript_fundamentals/destructuring_and_spreading.md
      - javascript_fundamentals/functional_programming.md
      - javascript_fundamentals/classes.md
      - javascript_fundamentals/document_object_model.md
  - React:
      - react/getting_started.md
      - react/setting_up.md
      - react/components.md
      - react/props.md
      - react/map_list_keys.md
      - react/hooks.md
      - react/events.md
      - react/forms.md
      - react/component_lifecycles.md
      - react/controlled_versus_uncontrolled.md
      - react/fetch_and_useQuery.md
      - react/react-router.md
      - react/context.md
      - react/custom_hooks.md
      - react/chakra-ui.md
      - react/project_structure.md
  - Clean Code:
      - clean_code/index.md
      - clean_code/javascript.md
