site_name: React Lecture
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - React:
      - react/getting_started.md
      - react/setting_up.md
      - react/components.md
      - react/props.md
      - react/map_list_keys.md
      - react/hooks.md
      - react/events.md
      - react/forms.md
      - react/component_lifecycles.md
      - react/controlled_versus_uncontrolled.md
      - react/context.md
      - react/custom_hooks.md
      - react/fetch_and_useQuery.md
      - react/react-router.md
      - react/chakra-ui.md
      - react/project_structure.md
  - Exercises:
      - exercises/index.md
      - exercises/01_javascript/index.md
